version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git submodule init
      - git submodule update
  build:
    commands:
      - cd codebuild-cloudfoundry
      - docker build -t aws-standard-ubuntu aws-codebuild-docker-images/ubuntu/standard/2.0
      - docker build -t codebuild-cloudfoundry ./
