version: 0.2

phases:
  install:
    commands:
      - cd fluentbit

  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - docker build -t aws-standard-ubuntu aws-codebuild-docker/ubuntu/standard/5.0
      - docker build -t $REPOSITORY_URI ./

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
