# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  web:
    image: amazon/aws-cli:latest
    stdin_open: true # equivalent of -i
    tty: true        # equivalent of -t
    command: help
