version: 0.2

phases:
  install:
    commands:
      - cd aws-ruby-node

  pre_build:
    commands:
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - docker build -t aws-standard-ubuntu aws-codebuild-docker/ubuntu/standard/5.0
      - docker build -t $REPOSITORY_URI ./

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
